title: Mark Sinkovics
email: sinkovics.mark@gmail.com
description: >
  This website contains my experiences around programming
baseUrl: ""
url: "https://marksinkovics.github.io"

github: [metadata]
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-timeago

# include: ['_pages']

permalink: pretty

kramdown:
  input: GFM

# Collection
collections:
  pages:
    output: true
    permalink: /
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
assets:
  prefix: "/assets"
  cache: false
  sources:
    - _assets/css
    - _assets/img
    - _assets/js
  # compression: true
  # gzip: true
  # source_maps: false


  exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - CNAME
  - LICENSE

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  enabled: true
  debug: false
  per_page: 2
  permalink: '/page/:num/'
  title: ':title'
  sort_reverse: true
  trail:
    before: 2
    after: 2
############################################################
