title: Mark Sinkovics - Personal site
author: Mark Sinkovics
twitter: marksinkovics
github: marksinkovics
linkedin: marksinkovics
email: sinkovics.mark@gmail.com
description: >
  This website contains my experiences around programming
baseUrl: ""
url: "https://marksinkovics.github.io"

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-timeago
  - jekyll-sitemap

# include: ['_pages']

permalink: pretty

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge

# Collection
collections:
  pages:
    output: true
    permalink: /
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

assets:
  prefix: "/assets"
  sources:
    - _assets/css
    - _assets/img
    - _assets/js
  source_maps: true
  exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - CNAME
  - LICENSE

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  enabled: true
  debug: false
  per_page: 10
  permalink: '/page/:num/'
  title: ':title'
  sort_reverse: true
  trail:
    before: 2
    after: 2
############################################################
